import express from "express";
import { Ollama } from "ollama";

const app = express();
app.use(express.json());

const ollama = new Ollama({ host: "http://localhost:11434" });

app.post("/chat", async (req, res) => {
  const { message } = req.body;
  const response = await ollama.chat({
    model: "llama3.2",
    messages: [{ role: "user", content: message }],
  });
  res.json({
    reply: response.message.content,
    disclaimer: "This response was generated by an AI model (Ollama).",
  });
});

app.listen(3000, () => console.log("Chatbot running on http://localhost:3000"));
